//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurappWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class foto
    {
        public foto()
        {
            this.recomendacion_foto = new HashSet<recomendacion_foto>();
            this.restaurante = new HashSet<restaurante>();
        }
    
        public long id { get; set; }
        public string nombre { get; set; }
        public string url { get; set; }
        public string url_min { get; set; }
        public string formato { get; set; }
        public long created_by { get; set; }
        public long updated_by { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
        public virtual ICollection<recomendacion_foto> recomendacion_foto { get; set; }
        public virtual ICollection<restaurante> restaurante { get; set; }
    }
}
