//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurappWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recomendacion_foto
    {
        public long id { get; set; }
        public long recomendacion_id { get; set; }
        public long foto_id { get; set; }
    
        public virtual foto foto { get; set; }
        public virtual recomendacion recomendacion { get; set; }
    }
}
