//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurappWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recomendacion
    {
        public recomendacion()
        {
            this.recomendacion_foto = new HashSet<recomendacion_foto>();
        }
    
        public long id { get; set; }
        public string comentario { get; set; }
        public int puntuacion { get; set; }
        public long usuario_id { get; set; }
        public long restaurante_id { get; set; }
        public long grupo_id { get; set; }
        public long created_by { get; set; }
        public long updated_by { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual grupo grupo { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual ICollection<recomendacion_foto> recomendacion_foto { get; set; }
        public virtual restaurante restaurante { get; set; }
        public virtual usuario usuario1 { get; set; }
        public virtual usuario usuario2 { get; set; }
    }
}
