//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurappWEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurappWEBEntities : DbContext
    {
        public RestaurappWEBEntities()
            : base("name=RestaurappWEBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<categoria> categoria { get; set; }
        public DbSet<distrito> distrito { get; set; }
        public DbSet<foto> foto { get; set; }
        public DbSet<grupo> grupo { get; set; }
        public DbSet<grupo_usuario> grupo_usuario { get; set; }
        public DbSet<migrations> migrations { get; set; }
        public DbSet<preferencia> preferencia { get; set; }
        public DbSet<recomendacion> recomendacion { get; set; }
        public DbSet<recomendacion_foto> recomendacion_foto { get; set; }
        public DbSet<restaurante> restaurante { get; set; }
        public DbSet<restaurante_categoria> restaurante_categoria { get; set; }
        public DbSet<usuario> usuario { get; set; }
    }
}
