//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurappWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class restaurante
    {
        public restaurante()
        {
            this.recomendacion = new HashSet<recomendacion>();
            this.restaurante_categoria = new HashSet<restaurante_categoria>();
        }
    
        public long id { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> latitud { get; set; }
        public Nullable<decimal> longitud { get; set; }
        public string descripcion { get; set; }
        public Nullable<long> foto_id { get; set; }
        public Nullable<decimal> puntuacion_total { get; set; }
        public long created_by { get; set; }
        public long updated_by { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual foto foto { get; set; }
        public virtual ICollection<recomendacion> recomendacion { get; set; }
        public virtual ICollection<restaurante_categoria> restaurante_categoria { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
