//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurappWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.categoria = new HashSet<categoria>();
            this.categoria1 = new HashSet<categoria>();
            this.foto = new HashSet<foto>();
            this.foto1 = new HashSet<foto>();
            this.grupo = new HashSet<grupo>();
            this.grupo1 = new HashSet<grupo>();
            this.grupo_usuario = new HashSet<grupo_usuario>();
            this.preferencia = new HashSet<preferencia>();
            this.recomendacion = new HashSet<recomendacion>();
            this.recomendacion1 = new HashSet<recomendacion>();
            this.recomendacion2 = new HashSet<recomendacion>();
            this.restaurante = new HashSet<restaurante>();
            this.restaurante1 = new HashSet<restaurante>();
            this.usuario1 = new HashSet<usuario>();
            this.usuario11 = new HashSet<usuario>();
        }
    
        public long id { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public Nullable<long> facebook_id { get; set; }
        public string password { get; set; }
        public string is_admin { get; set; }
        public string access_token { get; set; }
        public long created_by { get; set; }
        public long updated_by { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual ICollection<categoria> categoria { get; set; }
        public virtual ICollection<categoria> categoria1 { get; set; }
        public virtual ICollection<foto> foto { get; set; }
        public virtual ICollection<foto> foto1 { get; set; }
        public virtual ICollection<grupo> grupo { get; set; }
        public virtual ICollection<grupo> grupo1 { get; set; }
        public virtual ICollection<grupo_usuario> grupo_usuario { get; set; }
        public virtual ICollection<preferencia> preferencia { get; set; }
        public virtual ICollection<recomendacion> recomendacion { get; set; }
        public virtual ICollection<recomendacion> recomendacion1 { get; set; }
        public virtual ICollection<recomendacion> recomendacion2 { get; set; }
        public virtual ICollection<restaurante> restaurante { get; set; }
        public virtual ICollection<restaurante> restaurante1 { get; set; }
        public virtual ICollection<usuario> usuario1 { get; set; }
        public virtual usuario usuario2 { get; set; }
        public virtual ICollection<usuario> usuario11 { get; set; }
        public virtual usuario usuario3 { get; set; }
    }
}
